version: "3.9"

services:
  ged-front:
    image: "node:16"
    container_name: "ged-front"
    working_dir: "/project"
    env_file:
      - .env.local
    volumes:
      - "../:/project"
    command: >
      bash -c "npm i && npm run dev"
